### ISSUE TITLE
USER STORY: Manage a Poll

### ISSUE THREAD

**Issue by Viacheslav1510** [Viacheslav1510/running-love#4]
In order to  **automatically hide the poll** as an **administrator**, I can **pick the expiry date while publishing the poll**

## Acceptance Criteria:
- The poll should disappear at 11:59 PM on the target date
- The real estate of the "Poll" should be reserved on the home page
- The administrator expiry date should be at least 3 days after the current date.

## Tasks
- [x] Update the admin module view: the poll design
- [ ] Update the website view: show "Stay tuned, a new poll is coming soon" 
- [ ] Create a Javascript function to validate the expiry date is at least after 3 days
- [ ] Update the controller function
