### ISSUE TITLE
USER STORY: Create a Poll

### ISSUE THREAD

**Issue by Viacheslav1510** [Viacheslav1510/running-love#5]
In order to  **collect users feedback** as an **administrator**, I can **publish a poll**

## Acceptance Criteria:
- A poll should contain user experience
- A poll should collect user authorization

## Tasks
- [ ] Update the page for the poll view
- [ ] Make form authorization
- [ ] Create database for user authorization form
